services:
  postgres:
    container_name: SoftplanDesafioFullstack
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_BD: softplanFullstack